events {
    use epoll;
    worker_connections 1024;
}

worker_processes auto;
daemon off;
error_log off;
pid nginx.pid;

http {
    access_log off;

    server {
        listen 0.0.0.0:8080;
        return 200 "hello";
    }
}
